// lib/constants/vehicleClasses.js
export const VEHICLE_SPECS = {
  SEDAN: {
    label: 'Sedan',
    maxPassengers: 4,
    maxWheelchairs: 0,
    canDoTransfers: true,
    requiresD1: false,
    requiresPCV: false,
  },
  WAV_TAXI: {
    label: 'WAV Taxi',
    maxPassengers: 4,
    maxWheelchairs: 1,
    canDoTransfers: true,
    requiresD1: false,
    requiresPCV: false,
  },
  MPV_7_SEATER: {
    label: '7-Seater MPV',
    maxPassengers: 7,
    maxWheelchairs: 1,
    canDoTransfers: true,
    requiresD1: false,
    requiresPCV: false,
  },
  MINIBUS_9_SEATER: {
    label: '9-Seater Minibus',
    maxPassengers: 9,
    maxWheelchairs: 2,
    canDoTransfers: true,
    requiresD1: true,
    requiresPCV: false,
  },
  MINIBUS_15_SEATER: {
    label: '15-Seater Minibus (D1)',
    maxPassengers: 15,
    maxWheelchairs: 5,
    canDoTransfers: true,
    requiresD1: true,
    requiresPCV: false,
  },
  MIDIBUS_23_SEATER: {
    label: '23-Seater Midibus',
    maxPassengers: 23,
    maxWheelchairs: 5,
    canDoTransfers: true,
    requiresD1: false,
    requiresPCV: true,
  },
};