// registerDriver(driverData)
// getDriverProfile(driverId)
// updateDriverStatus(driverId, "online" / "offline")
// getAvailableJobs()
// placeBid(driverId, jobId, bidDetails)
// getDriverBids(driverId)
// withdrawBid(bidId)
